import type {
  ConsoleSessionId,
  CredentialId,
  FleetId,
  LeaseId,
  LocationKind,
  Scope,
  ShipId,
  ShipKind,
} from '@aeolus-fleet/common';

import type { ConsoleSession } from '../../core/identity/console-session.js';
import type { Credential } from '../../core/identity/credential.js';
import type { Fleet } from '../../core/registry/fleet.js';
import type { Lease } from '../../core/registry/lease.js';
import type { Ship } from '../../core/registry/ship.js';

// Maps database rows to domain objects. The casts to prefixed id types, kinds
// and scopes are safe: every id was generated by this server, and the enums and
// check constraints in the migrations admit nothing else.

export interface FleetRow {
  id: string;
  name: string;
  createdAt: Date;
}

export function toFleet(row: FleetRow): Fleet {
  return { id: row.id as FleetId, name: row.name, createdAt: row.createdAt };
}

export interface ShipRow {
  id: string;
  fleetId: string;
  name: string;
  type: string;
  kind: string;
  scopes: string[];
  note: string | null;
  createdAt: Date;
  retiredAt: Date | null;
}

export function toShip(row: ShipRow): Ship {
  return {
    id: row.id as ShipId,
    fleetId: row.fleetId as FleetId,
    name: row.name,
    type: row.type,
    kind: row.kind as ShipKind,
    scopes: row.scopes as Scope[],
    note: row.note,
    createdAt: row.createdAt,
    retiredAt: row.retiredAt,
  };
}

/** A lease as raw SQL returns it, with snake_case columns. */
export interface LeaseSqlRow {
  id: string;
  fleet_id: string;
  ship_id: string;
  location: string;
  location_description: string | null;
  started_at: Date;
  ended_at: Date | null;
}

export function toLease(row: LeaseSqlRow): Lease {
  return {
    id: row.id as LeaseId,
    fleetId: row.fleet_id as FleetId,
    shipId: row.ship_id as ShipId,
    location: { kind: row.location as LocationKind, description: row.location_description },
    startedAt: row.started_at,
    endedAt: row.ended_at,
  };
}

/** A credential as raw SQL returns it. */
export interface CredentialSqlRow {
  id: string;
  fleet_id: string;
  ship_id: string;
  secret_hash: string;
  issued_at: Date;
  claimed_at: Date | null;
  invalidated_at: Date | null;
}

export function toCredential(row: CredentialSqlRow): Credential {
  return {
    id: row.id as CredentialId,
    fleetId: row.fleet_id as FleetId,
    shipId: row.ship_id as ShipId,
    secretHash: row.secret_hash,
    issuedAt: row.issued_at,
    claimedAt: row.claimed_at,
    invalidatedAt: row.invalidated_at,
  };
}

/** A console session as raw SQL returns it. */
export interface ConsoleSessionSqlRow {
  id: string;
  fleet_id: string;
  ship_id: string;
  lease_id: string;
  token_hash: string;
  created_at: Date;
  last_used_at: Date;
  expires_at: Date;
  ended_at: Date | null;
}

export function toConsoleSession(row: ConsoleSessionSqlRow): ConsoleSession {
  return {
    id: row.id as ConsoleSessionId,
    fleetId: row.fleet_id as FleetId,
    shipId: row.ship_id as ShipId,
    leaseId: row.lease_id as LeaseId,
    tokenHash: row.token_hash,
    createdAt: row.created_at,
    lastUsedAt: row.last_used_at,
    expiresAt: row.expires_at,
    endedAt: row.ended_at,
  };
}

/** The ship a secret or a session token resolves to, as raw SQL returns it. */
export interface CallerSqlRow {
  ship_id: string;
  fleet_id: string;
  kind: string;
  scopes: string[];
}

export function toAuthenticatedShip(row: CallerSqlRow): {
  shipId: ShipId;
  fleetId: FleetId;
  kind: ShipKind;
  scopes: Scope[];
} {
  return {
    shipId: row.ship_id as ShipId,
    fleetId: row.fleet_id as FleetId,
    kind: row.kind as ShipKind,
    scopes: row.scopes as Scope[],
  };
}
