/**
 * Writes the aeolus plugin's crew-a-ship skill from the ship protocol the
 * fleet sends (packages/server/src/adapters/trpc/ship-protocol.ts), so the
 * plugin and the fleet state the protocol in one text. A test regenerates it
 * and fails when the committed skill differs.
 *
 * Usage: npm run generate:plugin-skill
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { SHIP_PROTOCOL } from '../packages/server/src/adapters/trpc/ship-protocol.ts';

export const PLUGIN_SKILL_PATH = fileURLToPath(new URL('../plugins/aeolus/skills/crew-a-ship/SKILL.md', import.meta.url));
export const CODEX_PLUGIN_SKILL_PATH = fileURLToPath(new URL('../plugins/aeolus/skills/aeolus-crew/SKILL.md', import.meta.url));

/** The skill: the fleet's protocol word for word, then how the plugin waits between turns. */
export function pluginSkill(): string {
  return [
    '---',
    'name: crew-a-ship',
    'description: How this session crews its Aeolus ship with the aeolus plugin - the ship protocol, the crew token from the identity file, and the watcher that wakes the session when deliveries wait. Use whenever you call the fleet (register, receive, ack, send, inbox, deregister) or the aeolus SessionStart hook says this folder crews a ship.',
    '---',
    '',
    '<!-- Generated by scripts/generate-plugin-skill.ts from the fleet\'s ship protocol. Do not edit by hand. -->',
    '',
    '# Crew an Aeolus ship',
    '',
    '## The ship protocol, as the fleet sends it',
    '',
    SHIP_PROTOCOL,
    '',
    '## With the aeolus plugin',
    '',
    'The plugin keeps this folder\'s ship for you, so the session goes on crewing it across /clear and restarts, and it wakes you when work arrives. Where it differs from the protocol above, this wins:',
    '',
    '1. Register only through /aeolus:crew. Afterwards the crew token is the crewToken line of this folder\'s identity file; the SessionStart hook names the file. Read it from there and pass it to every fleet call. Never register again while the file exists.',
    '2. Handle what waits: receive, ack each delivery (a ping gets pong instead, as rule 3 of the protocol says), act only if the ack succeeded, answer by senderName with inReplyTo. Receive again until it answers empty.',
    '   Every send states model: the exact model id this session runs now, as your system prompt names it (such as claude-opus-5-5), never an alias. After /model it is the new one. A send without it is refused.',
    '3. Do not keep calling receive to wait. Instead, start the watcher and end your turn: run "${CLAUDE_PLUGIN_ROOT}/scripts/aeolus-watch-status.sh"; unless it says watching, start "${CLAUDE_PLUGIN_ROOT}/scripts/aeolus-wait.sh" as a background task (run_in_background). It spends no tokens while it waits, and it keeps running across /clear.',
    '4. When the watcher finishes, you are woken with its output:',
    '   - "deliveries wait" (exit 0): go back to step 2, then step 3.',
    '   - "LEASE_ENDED" (exit 3): the operator released the ship. Say so, run "${CLAUDE_PLUGIN_ROOT}/scripts/aeolus-identity.sh" delete, and stop calling the fleet.',
    '   - "already watching" (exit 4): another watcher runs for this ship. Do nothing.',
    '   - "for almost 2 hours" (exit 6): start the watcher again, as in step 3. That is all.',
    '   - "this folder crews no ship" (exit 2) or "refused the crew token" (exit 5): say so and stop calling the fleet.',
    '5. A fleet call that answers LEASE_ENDED is handled as in step 4.',
    '6. To leave for good, use /aeolus:deregister.',
    '',
    '## A squadron member',
    '',
    'When this folder\'s identity file has a squadron line, the ship is a member of that squadron. Its flagship is the ship named as the squadron. Check in when crewed, and again after /clear, compact and resume, before anything else:',
    '',
    '1. Send the flagship (selector `{ "kind": "ship", "name": "<squadron>" }`) a message with contentType `application/vnd.aeolus.squadron.check-in+json` and payload `{"squadron":"<squadron>","model":"<model>"}`, where <model> is the exact model id this session runs, with a new idempotencyKey.',
    '2. Receive until the flagship answers it (inReplyTo your check-in) with contentType `application/vnd.aeolus.squadron.role+json`, and ack it. Its payload holds your role, the template it comes from, your charter, your check-in interval and your hand-offs. Take up the charter as your instructions. Each hand-off is the selector to send that hand-off to, as the charter refers to it by name.',
    '3. Answer the role message (inReplyTo set) with contentType `application/vnd.aeolus.squadron.on-station+json` and payload `{"squadron":"<squadron>","role":"<role>"}`. You are then on station.',
    '4. Report what you are doing with the report call (working, blocked or idle, and a short note) whenever it changes, and report at least once per check-in interval: a member that misses one interval is late, and three is silent.',
    '5. A message with contentType `application/vnd.aeolus.squadron.stand-down+json` from the flagship means the squadron stands down: ack it on receipt, as any delivery (the ack means received, not done), take no new work, and finish the work you hold. Then send the flagship a message with contentType `application/vnd.aeolus.squadron.stood-down+json`, payload `{"squadron":"<squadron>"}` and inReplyTo the stand-down, with a new idempotencyKey. squadrons then retires your ship once it holds no open deliveries; that ends your crew, so stop calling the fleet when it answers LEASE_ENDED.',
    '6. If the role message says `"standingDown": true`, the squadron already stands down: take up no new work, finish what you hold, and send stood-down as in step 5, inReplyTo the role message.',
    '',
  ].join('\n');
}

/** The Codex crew skill: the same protocol, with Codex hooks and an attached watcher between turns. */
export function codexPluginSkill(): string {
  return [
    '---',
    'name: aeolus-crew',
    'description: Crew an Aeolus ship from Codex with a Codex crew line, restore the folder identity and follow the fleet protocol. Use in Codex whenever the operator invokes $aeolus-crew, pastes a Codex crew line, or this folder already crews a ship.',
    '---',
    '',
    '<!-- Generated by scripts/generate-plugin-skill.ts from the fleet\'s ship protocol. Do not edit by hand. -->',
    '',
    '# Crew an Aeolus ship from Codex',
    '',
    '## The ship protocol, as the fleet sends it',
    '',
    SHIP_PROTOCOL,
    '',
    '## Start from a Codex crew line',
    '',
    'A Codex crew line is `$aeolus-crew <fleetUrl> <shipId> <secret> [<squadronId>]`. Never write the secret into a file and never repeat it in your answer.',
    '',
    'The SessionStart developer context must say `Aeolus Codex hooks are active` and give the plugin root, plugin data and working folder. If it does not, tell the operator to open `/hooks`, trust the Aeolus plugin hooks, start a new Codex task in this folder and paste the crew line again. Stop there.',
    '',
    '1. Run the plugin root\'s `scripts/aeolus-identity.sh show` with `AEOLUS_DATA` set to the named plugin data, `AEOLUS_FOLDER` set to the named working folder and `AEOLUS_HARNESS=codex`. If it shows a ship, this folder already crews it: say so, say one folder crews one ship and `$aeolus-deregister` frees it, then stop.',
    '2. Check that the fleet tools include `register`. If not, run `scripts/aeolus-mcp-hint.sh <fleetUrl>` with the same environment, show its exact answer and stop.',
    '3. Call `register` with the ship id, secret, the location where Codex runs and harness `codex`. A CONFLICT means another session crews it: tell the operator to release it in the console, get a new Codex crew line and paste that line here, then stop.',
    '4. Call `whoami` with the crew token. Run `scripts/aeolus-identity.sh write <fleetUrl> <shipId> <shipName> <crewToken> [<squadronId>]` with the same environment. Never pass the secret.',
    '5. Say which ship this folder now crews. For a squadron member, check in before anything else as below. Then receive and handle what waits.',
    '',
    '## With the Aeolus Codex plugin',
    '',
    '1. The crew token is the `crewToken` line of the identity file the SessionStart context names. Read it there and pass it to fleet calls. Never register again while the file exists.',
    '2. Receive, pong each operator ping, ack every other delivery and wait for the successful pong or ack before acting. Reply to `senderName` with `inReplyTo` set to `messageId`. Receive again until it answers empty.',
    '3. The trusted Codex PreToolUse hook replaces every Aeolus `send` input with the same input plus `model`, using the active model slug from Codex. Do not invent an alias. A send without the active model is refused.',
    '4. When work is done, end the turn. Do not claim automatic wake-up in this first slice. `$aeolus-watch` can keep a local turn attached to a token-free inbox wait. Codex Cloud has no automatic wake-up.',
    '5. On LEASE_ENDED, say the operator released the ship, run `scripts/aeolus-identity.sh delete` with the named environment and stop calling the fleet.',
    '6. Use `$aeolus-deregister` only to leave for good.',
    '',
    '## A squadron member',
    '',
    'When the identity file has a `squadron` line, check in when crewed and after startup, resume, clear or compact before anything else:',
    '',
    '1. Send the flagship named by `squadron` content type `application/vnd.aeolus.squadron.check-in+json` and payload `{"squadron":"<squadron>","model":"<model>"}` with the exact active model and a new idempotency key.',
    '2. Receive until the flagship answers with content type `application/vnd.aeolus.squadron.role+json`, then ack it. Take up its charter and hand-offs.',
    '3. Answer that role message with content type `application/vnd.aeolus.squadron.on-station+json`, payload `{"squadron":"<squadron>","role":"<role>"}` and `inReplyTo` set.',
    '4. Report working, blocked or idle whenever it changes and at least once per check-in interval.',
    '5. On `application/vnd.aeolus.squadron.stand-down+json`, ack on receipt, take no new work, finish held work, then send the flagship `application/vnd.aeolus.squadron.stood-down+json` with payload `{"squadron":"<squadron>"}` and `inReplyTo` the stand-down.',
    '6. If the role says `"standingDown": true`, take no new work and send stood-down in reply to the role message after finishing held work.',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(PLUGIN_SKILL_PATH, pluginSkill());
  writeFileSync(CODEX_PLUGIN_SKILL_PATH, codexPluginSkill());
  console.log(`Wrote ${PLUGIN_SKILL_PATH}`);
  console.log(`Wrote ${CODEX_PLUGIN_SKILL_PATH}`);
}
