/**
 * Writes the aeolus plugin's crew-a-ship skill from the ship protocol the
 * fleet sends (packages/server/src/adapters/trpc/ship-protocol.ts), so the
 * plugin and the fleet state the protocol in one text. A test regenerates it
 * and fails when the committed skill differs.
 *
 * Usage: npm run generate:plugin-skill
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { SHIP_PROTOCOL } from '../packages/server/src/adapters/trpc/ship-protocol.ts';

export const PLUGIN_SKILL_PATH = fileURLToPath(new URL('../plugins/aeolus/skills/crew-a-ship/SKILL.md', import.meta.url));

/** The skill: the fleet's protocol word for word, then how the plugin waits between turns. */
export function pluginSkill(): string {
  return [
    '---',
    'name: crew-a-ship',
    'description: How this session crews its Aeolus ship with the aeolus plugin - the ship protocol, the crew token from the identity file, and the watcher that wakes the session when deliveries wait. Use whenever you call the fleet (register, receive, ack, send, inbox, deregister) or the aeolus SessionStart hook says this folder crews a ship.',
    '---',
    '',
    '<!-- Generated by scripts/generate-plugin-skill.ts from the fleet\'s ship protocol. Do not edit by hand. -->',
    '',
    '# Crew an Aeolus ship',
    '',
    '## The ship protocol, as the fleet sends it',
    '',
    SHIP_PROTOCOL,
    '',
    '## With the aeolus plugin',
    '',
    'The plugin keeps this folder\'s ship for you, so the session goes on crewing it across /clear and restarts, and it wakes you when work arrives. Where it differs from the protocol above, this wins:',
    '',
    '1. Register only through /aeolus:crew. Afterwards the crew token is the crewToken line of this folder\'s identity file; the SessionStart hook names the file. Read it from there and pass it to every fleet call. Never register again while the file exists.',
    '2. Handle what waits: receive, ack each delivery, act only if the ack succeeded, answer by senderName with inReplyTo. Receive again until it answers empty.',
    '3. Do not keep calling receive to wait. Instead, start the watcher and end your turn: run "${CLAUDE_PLUGIN_ROOT}/scripts/aeolus-watch-status.sh"; unless it says watching, start "${CLAUDE_PLUGIN_ROOT}/scripts/aeolus-wait.sh" as a background task (run_in_background). It spends no tokens while it waits, and it keeps running across /clear.',
    '4. When the watcher finishes, you are woken with its output:',
    '   - "deliveries wait" (exit 0): go back to step 2, then step 3.',
    '   - "LEASE_ENDED" (exit 3): the operator released the ship. Say so, run "${CLAUDE_PLUGIN_ROOT}/scripts/aeolus-identity.sh" delete, and stop calling the fleet.',
    '   - "already watching" (exit 4): another watcher runs for this ship. Do nothing.',
    '   - "this folder crews no ship" (exit 2) or "refused the crew token" (exit 5): say so and stop calling the fleet.',
    '5. A fleet call that answers LEASE_ENDED is handled as in step 4.',
    '6. To leave for good, use /aeolus:deregister.',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(PLUGIN_SKILL_PATH, pluginSkill());
  console.log(`Wrote ${PLUGIN_SKILL_PATH}`);
}
